---
title: "sarima_2"
author: "Ling JIN"
date: "9 juin 2016"
output: html_document
---

```{r}
library("astsa")
library("zoo")

library("timeDate")
library("forecast")
library("tseries")#diff adf.test
rm(list=objects())
library(polynom)
library(magrittr)
library(parallel)
library(portes)

```

```{r}
setwd("~/Documents/python")
data = read.csv("sarima_6hours.csv",header = T, sep = ",")
typeof(data)#list
```

```{r}
sum = as.vector(data[,3])

date = strptime(data[,2], "%Y-%m-%d %H:%M:%S", tz = "")
```

```{r}
data = cbind(date, sum)
```

```{r}
# #estimates the number of seasonal differences.
# frequency(sum)#1
# nom_sum_diff = nsdiffs(sum)
```

```{r}
#Figure de serie

par(mfrow = c(1,1))
plot(date, sum, type='l')
tsdisplay(sum, main = "Figure de la serie de 2014 et 2015 par 6 heures ")
```

```{r}
#lag de différenciation est 4
ts_diff_4 = diff(sum,4)
plot(ts_diff_4, type = 'l')
tsdisplay(ts_diff_4, main = "Figure de serie avec une differenciation")
#C'est bon pour D et d
```

```{r}
#lag de différenciation est 4
ts_diff_4_4 = diff(ts_diff_4,4)
plot(ts_diff_4_4, type = 'l')
tsdisplay(ts_diff_4_4)
#C'est bon pour D et d
```

```{r}
#lag de différenciation est 7
ts_diff_4_7 = diff(ts_diff_4,7)
plot(ts_diff_4_7, type = 'l')
tsdisplay(ts_diff_4_7)

```

```{r}
#lag de différenciation est 1
ts_diff_4_7_1 = diff(ts_diff_4_7,1)
plot(ts_diff_4_7_1, type = 'l')
tsdisplay(ts_diff_4_7_1)

```

```{r}
#Dickey-Fuller(ADF) test standard reject non-trend stationarity
adf.test(ts_diff_4, alternative = "stationary", k = 0)

#Dickey-Fuller(ADF) test k = trunc((length(x)-1)^(1/3)) reject
adf.test(ts_diff_4, alternative = "stationary")

#Kwiatkowski-Phillioe_Schimidt-Shin(KPSS) accept a trend-stationarity!!!!!!
kpss.test(ts_diff_4)

#Phillips-Perron Test for Unit Roots reject
PP.test(ts_diff_4)

##result: stationary
```


```{r}
#lag de différenciation est 1: ACF a l'air pas stationaire
#ts_diff_1 = diff(sum,1)
#tsdisplay(ts_diff_1)
#résultat: on prend diff_4
```



```{r}
##Explanation of Arima: 
##If we differ the series by one lag, d is 1.
##If we do a seasonal difference, D is 1.
##So do not use differed series in Arima in R. If do that, the result is different.
##See Rob Hyndman's answer and O Texts
sum.ts <- ts(sum, frequency=4)
sumsea = seasadj(stl(sum.ts, s.window="periodic"))
fit = Arima(sumsea, order = c(11,0,6), seasonal = list(order = c(4,1,1), periode = 4))
#fit = Arima(sum, order = c(1,0,1), seasonal = list(order = c(1,1,1), periode = 4))
#residual test
tsdisplay(residuals(fit))
summary(fit)
Box.test(residuals(fit), lag = 20, type = "Ljung") #p-value 0.8848 there is no correlated residual
plot(forecast(fit,4*60))
```

```{r}
##Choose the best model
ordre<-expand.grid(p = c(9:16), q = c(5:10), P=c(3:5),Q=c(0:2))
ordre<-cbind(ordre[,1],0,ordre[,2],ordre[,3],1,ordre[,4])
dim(ordre)

##with optimization method CSS
sarima<-function(x,ordre,s)
{
  arima(x,order = ordre[1:3], seasonal = list(order = ordre[4:6], period = s),include.mean = F, method = "CSS")
}

model.sarima<-apply(ordre,1,sarima,x=sum,s=4)

aic<-lapply(model.sarima,function(x) x$aic)%>%unlist
bic<-lapply(model.sarima,function(x) -2*x$loglik+x$nobs*length(x$coef))%>%unlist
like<-lapply(model.sarima,function(x) -2*x$loglik)%>%unlist

##min AIC 1 5 2 1 
par(mfrow=c(1,1))
o<-order(bic)
plot(bic[o],type='b',pch=20,axes=F,xlab='')
axis(1,c(1:length(bic)),paste(ordre[o,1],ordre[o,3],ordre[o,4],ordre[o,6]),las=2)
axis(2)

ordre[which.min(aic),]
ordre[which.min(bic),]

##########pvalue du test de student
pvalue<-function(model)
{
  (1-pnorm(abs(model$coef)/sqrt(diag(model$var.coef))))*2
}

##min BIC model ma2,ma3,ma4 and sar2 are zero --> sarima(9,0,4)(3,1,0)
model.sarima[[which.min(bic)]]$coef
pvalue(model.sarima[[which.min(bic)]])
##########diagnostics des coefficients
abs(model.sarima[[which.min(bic)]]$coef)/sqrt(diag(model.sarima[[which.min(bic)]]$var.coef))<1.96


#######test de box pierce
pvalue_BP<-function(model,K)
{
  rho<-acf(model$residuals,lag.max=K,plot=F)$acf[-1]
  n<-model$nobs
  pval<-(1-pchisq(n*sum(rho^2),df=K-length(model$coef)))
  return(pval)
}

#etude des residus
#1
pvalue_BP(model.sarima[[which.min(bic)]],K=20) #8.026912e-13 non

par(mfrow=c(3,1))
acf(model.sarima[[which.min(bic)]]$residuals, main = "ACF")
pacf(model.sarima[[which.min(bic)]]$residuals, main = "PACF")# great

qqnorm(model.sarima[[which.min(bic)]]$residuals)
#2
#pvalue_BP(model.sarima[[order(aic)[2]]],K=20) #0.8658392 Yeahhhh

#par(mfrow=c(2,1))
#acf(model.sarima[[order(aic)[2]]]$residuals)
# pacf(model.sarima[[order(aic)[2]]]$residuals)# great
# qqnorm(model.sarima[[order(aic)[2]]]$residuals)

```

```{r}
##build time series of best order
fit.order = Arima(sumsea, order = c(9,0,5), seasonal = list(order = c(3,1,0), periode = 4))
##forecast
plot(forecast(fit.order, 4*60))
plot.forecast(model.sarima[[which.min(bic)]])
fore_sarima = predict(model.sarima[[which.min(bic)]], 4*2*365+7*4 )
summary(fore_sarima)
pre_semaine = as.numeric(fore_sarima$pred)

par(mfrow=c(1,1))
plot(sum, type = 'l', col = 'red', main = "Prevision d'une annee plus une semaine la serie")
lines(pre_semaine, col = 'blue')

residu = abs(sum - pre_semaine)

fore_se = fore_sarima$se
fore_se
```

```{r}
fit_fore = forecast(fit, h=358)
summary(fit_fore)
fit_fore_mean = fit_fore$mean
fit_fore_res = fit_fore$residuals
```

```{r}
#first 358 jours 
first_358 = sum[1:358]
fore = as.numeric(fit_fore_mean + first_358)
fore_res = fore - sum[1:358]
plot(fore, type = 'l' )
lines(sum, col = 'red' )
```


```{r}
fit2 = Arima(ts_diff_7, order = c(3,1,4), seasonal = c(2,1,0,7))
tsdisplay(residuals(fit2))
summary(fit2)
Box.test(residuals(fit2), lag = 20, type = "Ljung")
plot(forecast(fit2, h=52*7))
```

